agent1.sources = python-api-source
agent1.channels = mem-channel
agent1.sinks = kafka-sink


agent1.sources.python-api-source.type = exec
agent1.sources.python-api-source.command = python /home/bigdata/api.py


agent1.channels.mem-channel.type = memory
agent1.channels.mem-channel.capacity = 1000
agent1.channels.mem-channel.transactionCapacity = 100


agent1.sinks.kafka-sink.type = org.apache.flume.sink.kafka.KafkaSink
agent1.sinks.kafka-sink.kafka.bootstrap.servers = localhost:9092
agent1.sinks.kafka-sink.kafka.topic = user-events
agent1.sinks.kafka-sink.flumeBatchSize = 20


agent1.sources.python-api-source.channels = mem-channel
agent1.sinks.kafka-sink.channel = mem-channel
