agent2.sources = kafka-source
agent2.channels = hdfs-mem-channel
agent2.sinks = hdfs-sink


agent2.sources.kafka-source.type = org.apache.flume.source.kafka.KafkaSource
agent2.sources.kafka-source.kafka.bootstrap.servers = localhost:9092
agent2.sources.kafka-source.kafka.topics = user-events
agent2.sources.kafka-source.kafka.consumer.group.id = flume-hdfs-consumer


agent2.channels.hdfs-mem-channel.type = memory
agent2.channels.hdfs-mem-channel.capacity = 10000
agent2.channels.hdfs-mem-channel.transactionCapacity = 1000


agent2.sinks.hdfs-sink.type = hdfs

agent2.sinks.hdfs-sink.hdfs.path = hdfs://localhost:9000/user/bigdata/user_events_raw/year=%Y/month=%m/day=%d/
agent2.sinks.hdfs-sink.hdfs.filePrefix = user-data-
agent2.sinks.hdfs-sink.hdfs.fileType = DataStream


agent2.sinks.hdfs-sink.hdfs.rollInterval = 60
agent2.sinks.hdfs-sink.hdfs.rollSize = 1048576
agent2.sinks.hdfs-sink.hdfs.rollCount = 0
agent2.sinks.hdfs-sink.hdfs.useLocalTimeStamp = true


agent2.sources.kafka-source.channels = hdfs-mem-channel
agent2.sinks.hdfs-sink.channel = hdfs-mem-channel
